-- 003_reset_pdfs.sql
-- Clears existing PDF URLs so the pipeline regenerates all PDFs with the new template
update prospect_audits set pdf_url = null, pdf_filename = null;

-- Rollback: n/a (data is regenerated by running the pipeline)
